services:
  - type: web
    name: lb-cosmetics
    runtime: static
    branch: main
    buildCommand: ""
    staticPublishPath: .
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
